version: '3.8'

volumes: 
  influxdb_data: {}
  influxdb_conf: {}
  influxdb_init: {}
  edge_influxdb_data: {}
  edge_influxdb_conf: {}
  edge_influxdb_init: {}
  edge_mongodb_data: {}

services:
  # CLOUD
  cloud-gateway:
    container_name: cloud-gateway
    image: gateway
    build:
      context: Cloud/Gateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001
    env_file:
      - Cloud/Gateway/gateway.env
    depends_on:
      - cloud-user-management
      - cloud-notification
      - cloud-device-management
      - cloud-sensor-data
      - cloud-mqtt

  cloud-user-management:
    container_name: cloud-user-management
    image: usermanagement
    build:
      context: Cloud/UserManagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - Cloud/UserManagement/user-management.env

  cloud-notification:
    container_name: cloud-notification
    image: notification
    build:
      context: Cloud/Notification
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    env_file:
      - Cloud/Notification/notification.env
  
  cloud-device-management:
    container_name: cloud-device-management
    image: devicemanagement
    build: 
      context: Cloud/DeviceManagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    env_file:
      - Cloud/DeviceManagement/device-management.env

  cloud-sensor-data:
    container_name: cloud-sensor-data
    image: sensordata
    build: 
      context: Cloud/SensorData
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3003:3003
    env_file:
      - Cloud/SensorData/sensor-data.env
    depends_on:
      - cloud-influxdb
  
  cloud-influxdb:
    container_name: cloud-influxdb
    image: influxdb:alpine
    ports: 
      - 8086:8086
    volumes: 
      - influxdb_data:/var/lib/influxdb
    
  cloud-mqtt:
    container_name: cloud-mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9002:9001
    volumes:
      - ./Cloud/volumes/config:/mosquitto/config
    

  # EDGE
  edge-gateway:
    container_name: edge-gateway
    image: edge-gateway
    build:
      context: Edge/Gateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
    env_file:
      - Edge/Gateway/edge-gateway.env
    depends_on:
      - edge-mqtt

  edge-mqtt:
    container_name: edge-mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1884:1884
      - 9003:9001
    volumes:
      - ./Edge/volumes/config:/mosquitto/config
  
  edge-persistence:
    container_name: edge-persistence
    image: edge-persistence
    build: 
      context: Edge/persistence
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5002:5002
    env_file:
      - Edge/Persistence/edge-persistence.env
    depends_on:
      - edge-influxdb
      - edge-mqtt

  edge-influxdb:
    container_name: edge-influxdb
    image: influxdb:alpine
    ports: 
      - 8087:8086
    volumes: 
      - edge_influxdb_data:/var/lib/influxdb

  edge-device-management:
    container_name: edge-device-management
    image: edge-devicemanagement
    build: 
      context: Edge/DeviceManagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5003:5003
    env_file:
      - Edge/DeviceManagement/edge-device-management.env
  
  edge-analytics:
    container_name: edge-analytics
    image: edge-analytics
    build: 
      context: Edge/analytics
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5004:5004
    env_file:
      - Edge/Analytics/edge-analytics.env
    depends_on:
      - edge-mqtt

  edge-mongodb:
    container_name: edge-mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    volumes:
      - edge_mongodb_data:/data/db