version: '3.4'

services:
  cloud-gateway:
    image: gateway
    build:
      context: Cloud/Gateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file:
      - Cloud/Gateway/gateway.env

  user-management:
    image: usermanagement
    build:
      context: Cloud/UserManagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
    - 3000:3000
    env_file:
    - Cloud/UserManagement/user-management.env

  notification:
    image: notification
    build:
      context: Cloud/Notification
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
    - 3001:3001
    env_file:
    - Cloud/Notification/notification.env     