version: '3.8'

volumes: 
  influxdb_data: {}
  influxdb_conf: {}
  influxdb_init: {}

services:
  cloud-gateway:
    image: gateway
    build:
      context: Cloud/Gateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file:
      - Cloud/Gateway/gateway.env
    depends_on:
      - user-management
      - notification

  user-management:
    image: usermanagement
    build:
      context: Cloud/UserManagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - Cloud/UserManagement/user-management.env

  notification:
    image: notification
    build:
      context: Cloud/Notification
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    env_file:
      - Cloud/Notification/notification.env
  
  cloud-device-management:
    image: devicemanagement
    build: 
      context: Cloud/devicemanagement
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    env_file:
      - Cloud/DeviceManagement/device-management.env
  
  influxdb:
    image: influxdb:latest-alpine
    ports: 
      - 8086:8086
    restart: always
    volumes: 
      - influxdb_data:/var/lib/influxdb
    
    